name: build, release and publish

on:
  push:
    branches:
     - main
    tags:
      - v*

permissions:
  contents: write

jobs:

  build:
    uses: './.github/workflows/build.yml'
    secrets: inherit

  release:
    needs: build
    uses: './.github/workflows/release.yml'

  publish:
    needs: release
    permissions:
      id-token: write
      contents: read
    uses: './.github/workflows/publish.yml'
